server:
  port: 5123
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27123/andy-springboot3-template-local
    redis:
      database: 0
      host: localhost
      port: 6123
      password: aredissecret
      timeout: 10000
  kafka:
    bootstrap-servers: localhost:9123
